# Generated by Django 4.1 on 2022-12-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='webp_image',
            field=models.ImageField(default='', upload_to='images', verbose_name='Изображение WEBP'),
            preserve_default=False,
        ),
    ]
