# Generated by Django 4.1 on 2022-12-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_webp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение WEBP'),
        ),
    ]
